CREATE DATABASE LAB01;
USE LAB01;
CREATE TABLE EMPLOYEE(
    CODE VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(20),
    DOB DATE,
	SALARY FLOAT
    );

INSERT INTO EMPLOYEE(CODE,NAME,DOB,SALARY)
    VALUES ('E001','MARIAM','1990-05-08',70000),
     ('E002','CAREL','1993-10-24',55000);


 CREATE TABLE CUR( NAME VARCHAR(20),DOB DATE, SALARY FLOAT);

DELIMITER //
CREATE PROCEDURE IMP()
    BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE emp_name VARCHAR(20);
	DECLARE emp_dob DATE;
	DECLARE emp_salary FLOAT;
	DECLARE emp_record CURSOR FOR SELECT NAME, DOB, SALARY FROM EMPLOYEE;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE= TRUE;
	OPEN emp_record;
	read_loop:LOOP
	FETCH emp_record INTO emp_name,emp_dob,emp_salary;
	IF done THEN
	LEAVE read_loop;
	END IF;
	INSERT INTO CUR VALUES(emp_name,emp_dob,emp_salary);
    END LOOP;
    CLOSE emp_record;
	END;//

 DELIMITER ;
 CALL IMP();

SELECT *FROM CUR;
