USE LAB01;
CREATE TABLE SAILORS(
	SID INT PRIMARY KEY,
	SNAME CHAR(25),
	RATING FLOAT,
	AGE INT);
    
INSERT INTO SAILORS VALUES ('70001','KEN',2.9,50);
INSERT INTO SAILORS VALUES ('70002','KHAI',4.2,42);
INSERT INTO SAILORS VALUES ('70003','JIMM',3.5,39);

 CREATE TABLE BOATS(
	BID INT PRIMARY KEY,
	BNAME CHAR(20),
	COLOUR CHAR(10)
 );
 
 INSERT INTO BOATS VALUES ('001','SPIRIT','BLACK');
 INSERT INTO BOATS VALUES ('005','ESCAPE','PURPLE');
 INSERT INTO BOATS VALUES ('009','LIBERTY','GREEN');

  CREATE TABLE RESERVES(
		SID INT,
		BID INT,
		DAY DATE
 );
 
INSERT INTO RESERVES VALUES ('70003','001','2021/01/10');
INSERT INTO RESERVES VALUES ('70003','005','2021/01/11');
INSERT INTO RESERVES VALUES ('70001','009','2021/01/10');
INSERT INTO RESERVES VALUES ('70001','009','2021/01/11');

#1
SELECT A.SID, A.SNAME, A.RATING, A.AGE
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID = C.SID AND C.BID = 001;

#2
SELECT B.BNAME
FROM RESERVES AS C
INNER JOIN SAILORS AS A ON A.SID =C.SID AND A.SNAME='JIMM'
INNER JOIN BOATS AS B ON B.BID=C.BID;

#3
SELECT A.SNAME
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID = C.SID
INNER JOIN BOATS AS B ON B.BID = C.BID AND B.COLOUR = 'BLACK'
ORDER BY A.AGE;

#4
SELECT DISTINCT A.SNAME
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID IN (C.SID);

#5
SELECT A.SID , A.SNAME
FROM RESERVES AS C
INNER JOIN RESERVES AS D ON C.SID <> D.SID AND C.DAY=D.DAY
INNER JOIN SAILORS AS A ON D.SID=A.SID;
