USE lab;
#a
CREATE TABLE STUDENT(
	sno INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    marks INT NOT NULL,
    dept VARCHAR(20) NOT NULL
);

#b
ALTER TABLE STUDENT ADD COLUMN age INT NOT NULL;

#c
ALTER TABLE STUDENT MODIFY COLUMN dept VARCHAR(10);

#d
ALTER TABLE STUDENT DROP COLUMN marks;

#e
RENAME TABLE STUDENT TO STUDENTS;

#f
TRUNCATE TABLE STUDENTS;

#g
DROP TABLE STUDENTS;

